# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Riviera17' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Riviera17
  pod 'Alamofire', '~> 4.0'
  pod ‘SWRevealViewController’


  target 'Riviera17Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Riviera17UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
